name: autofix.ci

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['22.14.0']

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Enable corepack
        run: corepack enable & corepack install

      - name: Install dependencies
        run: pnpm i

      - name: Lint
        run: pnpm format && pnpm lint

      - uses: autofix-ci/action@551dded8c6cc8a1054039c8bc0b8b48c51dfc6ef
        with:
          commit-message: 'style: fix lint errors'
          comment: '🎨 Auto fix lint errors'

      - name: Unit test
        run: pnpm test:cov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
